apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rdrw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-60-tenant/load-app-8acde1df-63aa-4035-b65c-44edfe8e30d3/devfile-sample-rdrw@sha256:13f04b52c2fc1da06bdd3fc1bd36db536d977f1b8a7e31f8ca34e7fd0ab36561
        name: my-nodejs
        resources: {}
status: {}
